language: python
python: 
  - "3.5"
sudo: false

install:
  - pip install coverage coveralls tox
script:
  - tox
after_success:
  - coveralls

env:
  - TOXENV=py27-django18
  - TOXENV=py27-django19
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py27-djangolatest

  - TOXENV=py33-django18

  - TOXENV=py34-django18
  - TOXENV=py34-django19
  - TOXENV=py34-django110
  - TOXENV=py34-django111
  - TOXENV=py34-djangolatest

  - TOXENV=py35-django18
  - TOXENV=py35-django19
  - TOXENV=py35-django110
  - TOXENV=py35-django111
  - TOXENV=py35-djangolatest

  - TOXENV=pypy-django18
  - TOXENV=pypy-django19
  - TOXENV=pypy-django110
  - TOXENV=pypy-django111
  - TOXENV=pypy-djangolatest

  - TOXENV=docs
