language: python
cache: pip
sudo: false

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"

env:
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
  - DJANGO=3.0

matrix:
  fast_finish: true
  exclude:
    - { python: "2.7", env: DJANGO=2.0 }
    - { python: "2.7", env: DJANGO=2.1 }
    - { python: "2.7", env: DJANGO=2.2 }
    - { python: "2.7", env: DJANGO=3.0 }

    - { python: "3.4", env: DJANGO=2.1 }
    - { python: "3.4", env: DJANGO=2.2 }
    - { python: "3.4", env: DJANGO=3.0 }

    - { python: "3.5", env: DJANGO=3.0 }

install:
  - pip install coverage coveralls tox tox-travis

script:
  - tox

after_success:
  - coveralls
  - pip install codecov
  - codecov -e TOXENV,DJANGO
