language: python
cache: pip
sudo: false

python: 
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.8
  - DJANGO=1.9
  - DJANGO=1.10
  - DJANGO=1.11
  - DJANGO=2.0
  - DJANGO=2.1

matrix:
  fast_finish: true
  exclude:
    - { python: "2.7", env: DJANGO=2.0 }
    - { python: "2.7", env: DJANGO=2.1 }
    - { python: "3.4", env: DJANGO=2.1 }
    - { python: "3.6", env: DJANGO=1.8 }
    - { python: "3.6", env: DJANGO=1.9 }
    - { python: "3.6", env: DJANGO=1.10 }

install:
  - pip install coverage coveralls tox tox-travis

script:
  - tox

after_success:
  - coveralls
  - pip install codecov
  - codecov -e TOXENV,DJANGO

